version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gol
    main: ./frontend
    binary: gol
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: arm

archives:
  - id: binaries
    formats:
      - binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^bin"
